### PR TITLE
fix: add VMware logo

### LINKED ISSUE #5293: Replace Litmus Logo with VMware Logo in Chaos Fault Cards inside ChaosCenter
## Description
In **ChaosCenter → Chaos Hub → Default Chaos Hub**, there are multiple fault categories such as AWS, Azure, GCP, Kubernetes, Load, Spring Boot, VMware, etc.  

When navigating to the **Chaos Faults** section inside the **Default Chaos Hub**, you’ll see **1 fault card** for VMware.  Currently, each of these fault cards displays the **Litmus logo**, which needs to be updated.

### Required Change
- Replace the **Litmus logo** in the **1 Chaos Fault card** with the **VMware logo**  [logo link](https://hub.litmuschaos.io/api/icon/3.22.0/vmware/vmware.png)
- Ensure the new logo is properly sized and aligned within each fault card.

## Location
ChaosCenter → Chaos Hub → Default Chaos Hub → Chaos Faults (VMware category)

Image

## Expected Behavior
- The **VMware logo** should replace the existing Litmus logo under the VMware fault category.  
- The logo should be clearly visible, properly aligned, and consistent with the design style of other category cards.

### PR DESCRIPTION
**Pull request by adi-ray**
Fixes #5293 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: chaoscenter/web/src/views/ChaosHub/ChaosFaults/ChaosFaults.tsx [hunk 1]
```diff
@@ -101,24 +101,20 @@ function ChaosFaults({ hubDetails, faultCategories, loading, searchValue }: Chao
...
             <Layout.Horizontal spacing="small">
-              {fault.chartName.toLowerCase() === 'kubernetes' || fault.chartName.toLowerCase() === 'spring-boot' || fault.chartName.toLowerCase() === 'k6-loadgen' || fault.chartName.toLowerCase() === 'azure' || fault.chartName.toLowerCase() === 'gcp' || fault.chartName.toLowerCase() === 'aws' || fault.chartName.toLowerCase() === 'k6-logo' ? (
+              {['kubernetes', 'spring-boot', 'k6-loadgen', 'azure', 'gcp', 'aws', 'k6-logo', 'vmware'].includes(
+                fault.chartName.toLowerCase()
+              ) ? (
                 <img
                   src={
-                    isDefault === 'true'
+                    fault.chartName.toLowerCase() === 'vmware'
+                      ? 'https://hub.litmuschaos.io/api/icon/3.22.0/vmware/vmware.png'
```
Comment (bmscomp) [inline chaoscenter/web/src/views/ChaosHub/ChaosFaults/ChaosFaults.tsx:110]: I think it's better to get an SVG inlined content in the image tag, or download the image and put in resources, because in some environment we do not have public internet access, the same thing we will need sometime to make an offline installation in some cases

Comment (PriteshKiri) [reply chaoscenter/web/src/views/ChaosHub/ChaosFaults/ChaosFaults.tsx:110]: I agree. We will update all the images to SVG in the upcoming releases. Thanks for sharing your thoughts @bmscomp

**Comment by PriteshKiri** [comment]
Hey @adi-ray 

Could you please resolve the conflicts?
