### PR TITLE
chore (litmus-portal): Header updates for project switching, necessary bug fixes for it and disabling notifications button in header.

### LINKED ISSUE #1996: Project switching required for litmus-portal and disable notifications.
Project switching required for litmus-portal and disable notifications.

### PR DESCRIPTION
**Pull request by ishangupta-ds**
## Proposed changes

This PR adds project switching feature from the UI also adds necessary checks required for project selection . Also disables notifications.

fixes #1996

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Dependency
- PR #1982 

## Special notes for your reviewer:
Needed for this release / RC1

### CODE REVIEW

**Comment by ishangupta-ds** [comment]
@arkajyotiMukherjee @S-ayanide @gdsoumya @amityt @rajdas98 @Sanjay1611 @Saranya-jena @Jonsy13 @oumkale  PTAL.

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx [hunk 1]
```diff
@@ -147,43 +153,40 @@ function ProfileInfoDropdownItems(props: ProfileInfoDropdownItemProps) {
             >
               Edit Profile
             </Button>
+
+            <Button
+              disabled={loggedOut}
+              size="small"
+              onClick={logOut}
+              classes={{ root: classes.buttonSignout }}
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx:161]: What is the purpose of adding the key `root` here?

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx [hunk 2]
```diff
@@ -147,43 +153,40 @@ function ProfileInfoDropdownItems(props: ProfileInfoDropdownItemProps) {
...
-          {projects.length === 0 ? (
+          {switchableProjects.length === 0 ? (
             <ListItem>
               <ListItemText>
                 You haven&apos;t created any projects yet.
               </ListItemText>
             </ListItem>
           ) : (
-            projects.map((element: any, index: any) => (
+            switchableProjects.map((element: any, index: any) => (
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx:176]: Can you give `element` and `index` a type and change it from `any`!

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownSection.tsx [hunk 3]
```diff
@@ -42,53 +49,40 @@ const ProfileDropdownSection: React.FC<ProfileInfoDropdownSectionProps> = ({
...
-              fontSize: 12,
-              color: 'grey',
-            }}
-          >
-            {username}
+          <Typography>
+            {name}{' '}
+            <IconButton
+              edge="end"
+              ref={profileMenuRef as any}
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownSection.tsx:65]: Don't use `any`

File: litmus-portal/frontend/src/models/header.ts [hunk 4]
```diff
@@ -3,19 +3,12 @@ export interface NotificationIds {
...
-  projectName: string;
-  statusActive: string;
-  id: string;
-}
-
 export interface Message {
   sequenceID: string;
   id: string;
-  workflowName: string;
+  MessageType: string;
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/models/header.ts:9]: Can you keep the first character in lower case to match the convention!

**Review by S-ayanide — CHANGES_REQUESTED** [review]

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx (hunk 1 above)
Comment (ishangupta-ds) [reply litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx:161]: Removed.

**Comment by ishangupta-ds** [comment]
changes have been made PTAL @S-ayanide @rajdas98 @Sanjay1611 @Saranya-jena

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx [hunk 5]
```diff
@@ -85,6 +83,22 @@ function ProfileInfoDropdownItems(props: ProfileInfoDropdownItemProps) {
...
   };
 
+  useEffect(() => {
+    const projectsAvailableForSwitching: Project[] = [];
+    projects.forEach((project) => {
+      const memberList: Member[] = project.members;
+      memberList.forEach((member) => {
+        if (
+          member.user_name === username &&
+          (member.invitation === 'Accepted' || member.invitation === '')
```
Comment (Sanjay1611) [inline litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx:93]: The empty condition has to be removed

Comment (ishangupta-ds) [reply litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx:93]: okay @Sanjay1611 i am removing it then, we should merge the backend PR for auth first in that case @rajdas98

File: litmus-portal/frontend/src/redux/reducers/user.ts [hunk 6]
```diff
@@ -7,8 +7,10 @@ import createReducer from './createReducer';
 const initialState: UserData = {
   selectedProjectID: '',
   token: '',
-  username: '',
+  username: 'admin',
```
Comment (Sanjay1611) [inline litmus-portal/frontend/src/redux/reducers/user.ts:10]: Why aren't we initiating as empty string?

Comment (ishangupta-ds) [reply litmus-portal/frontend/src/redux/reducers/user.ts:10]: when the welcome modal is displayed if we initiate with empty string it will show no default username to the user on the header as we have kept welcome modal over the home page so header is visible there..this is just a default start variable used for UI, it has nothing to do with any backend interaction. @Sanjay1611 cc: @rajdas98

**Comment by ishangupta-ds** [comment]
@Sanjay1611 PTAL cc: @rajdas98 , have removed the empty invitation check for admin, we need to merge the backend teaming pr first.

**Comment by Sanjay1611** [comment]
> @Sanjay1611 PTAL cc: @rajdas98 , have removed the empty invitation check for admin, we need to merge the backend teaming pr first.

Okay so we will merge the auth PR first then the backend teaming and after that this PR

File: litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx (hunk 5 above)
Comment (ishangupta-ds) [reply litmus-portal/frontend/src/containers/layouts/Header/ProfileDropdownItems.tsx]: PR #1982 @rajdas98 cc: @Sanjay1611

**Comment by ishangupta-ds** [comment]
> > @Sanjay1611 PTAL cc: @rajdas98 , have removed the empty invitation check for admin, we need to merge the backend teaming pr first.
> 
> Okay so we will merge the auth PR first then the backend teaming and after that this PR

sure @Sanjay1611 cc: @rajdas98

File: litmus-portal/frontend/src/containers/layouts/Header/NotificationDropdown.tsx [hunk 7]
```diff
@@ -97,11 +100,10 @@ const NotificationsDropdown: React.FC<NotificationDropdownProps> = ({
               </ListItemText>
             </ListItem>
           ) : (
-            messages.map((element: any, index: any) => (
+            messages.map((element: any) => (
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/containers/layouts/Header/NotificationDropdown.tsx:103]: Can you change the `any` type here!

**Review by S-ayanide — CHANGES_REQUESTED** [review]

File: litmus-portal/frontend/src/containers/layouts/Header/styles.ts [hunk 8]
```diff
@@ -125,6 +143,7 @@ const useStyles = makeStyles((theme: Theme) => ({
     paddingBottom: theme.spacing(1),
     paddingLeft: theme.spacing(9),
     paddingRight: theme.spacing(9.5),
+    color: '#EB5757',
```
Comment (S-ayanide) [inline litmus-portal/frontend/src/containers/layouts/Header/styles.ts:146]: Can you take this color from theme?

File: litmus-portal/frontend/src/containers/layouts/Header/index.tsx [hunk 9]
```diff
@@ -154,8 +135,13 @@ const Header: React.FC = () => {
 
   useEffect(() => {
     fetchRandomMessages();
-    fetchRandomProjects();
-  }, [fetchRandomMessages, fetchRandomProjects]);
+  }, [fetchRandomMessages]);
+
+  useEffect(() => {
+    setSelectedProject(userData.selectedProjectID);
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/containers/layouts/Header/index.tsx:141]: have these three in an object

**Review by S-ayanide — CHANGES_REQUESTED** [review]

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]

**Comment by ishangupta-ds** [comment]
Changes made @arkajyotiMukherjee and @S-ayanide PTAL. cc: @rajdas98

**Comment by ishangupta-ds** [comment]
Screenshot 2020-09-09 at 2 21 03 PM

@rajdas98

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by amityt — APPROVED** [review]

**Review by Sanjay1611 — APPROVED** [review]

**Review by rajdas98 — APPROVED** [review]
