### PR TITLE
chore(Litmus Portal) : Teamming UI screens and other Fixes 

### LINKED ISSUE #1937: UI screens for teaming tab (Settings)

### PR DESCRIPTION
**Pull request by Saranya-jena**
Signed-off-by: Saranya-jena <saranya.jena@mayadata.io>

## Proposed changes
This PR contains:
- Added loader to welcome modal so that it won't pop up every time the homepage is rendered.
- Added UI screens for Teaming tab
- Refactored code for user management table and added pagination to the tables

Summarize your changes here to communicate with the maintainers and make sure to put the link of that issue
This PR fixes #1937 and #1938 

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Received/index.tsx [hunk 1]
```diff
@@ -0,0 +1,100 @@
+/* eslint-disable camelcase */
```
Comment (amityt) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Received/index.tsx:1]: We have made some changes in the eslint file, so this can be removed.

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx [hunk 2]
```diff
@@ -0,0 +1,165 @@
+/* eslint-disable camelcase */
```
Comment (amityt) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx:1]: Same here.

File: litmus-portal/backend/auth/pkg/utils/invite/invite.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+
+	templateData := struct {
+		Username string
+		Password string
+	}{
+		Username: username,
+		Password: password,
+	}
+	r := NewRequest(recipients, "Litmus Portal")
+	if err := r.ParseTemplate("/home/saranyaj/MayaData/my work(active)/litmus/litmus-portal/backend/auth/pkg/utils/invite/templates/template.html", templateData); err == nil {
```
Comment (ishangupta-ds) [inline litmus-portal/backend/auth/pkg/utils/invite/invite.go:57]: can you change this parse template directory to something more generic? cc: @rajdas98 @Sanjay1611 @gdsoumya

File: litmus-portal/backend/auth/pkg/utils/invite/templates/template.html [hunk 4]
```diff
@@ -0,0 +1,13 @@
+<!DOCTYPE html
+    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
+<html xmlns="http://www.w3.org/1999/xhtml">
+</head>
+<body>
+<p>
+    Hello {{.Username}} Here's the link to 
+    <a href="http://localhost:3001/login?#name={{.Username}}&email={{.Password}}" onclick="">Login</a>
```
Comment (ishangupta-ds) [inline litmus-portal/backend/auth/pkg/utils/invite/templates/template.html:8]: will it be local host for the portal?

**Review by ishangupta-ds — DISMISSED** [review]
Changes required.

File: litmus-portal/backend/auth/pkg/utils/invite/templates/template.html (hunk 4 above)
Comment (ishangupta-ds) [reply litmus-portal/backend/auth/pkg/utils/invite/templates/template.html:8]: @Sanjay1611 @gdsoumya @rajdas98 @Saranya-jena

Comment (Saranya-jena) [reply litmus-portal/backend/auth/pkg/utils/invite/templates/template.html:8]: Yes this we need to change, it's the link for login page in my case.

Comment (ishangupta-ds) [reply litmus-portal/backend/auth/pkg/utils/invite/templates/template.html:8]: Yeah IP is required.

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Received/index.tsx [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+import userAvatar from '../../../../../../utils/user';
+import ButtonFilled from '../../../../../Button/ButtonFilled';
+import useStyles from './styles';
+
+interface UserInvite {
+  _id: string; // eslint-disable-line no-eval
+  username: string;
+  email: string;
+  name: string;
+  logged_in: boolean; // eslint-disable-line no-eval
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Received/index.tsx:22]: these eslint-disables are not required also

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/index.tsx [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+import useStyles from './styles';
+
+interface UserInvite {
+  _id: string; // eslint-disable-line no-eval
+  username: string;
+  email: string;
+  name: string;
+  logged_in: boolean; // eslint-disable-line no-eval
+  created_at: string; // eslint-disable-line no-eval
+  updated_at: string; // eslint-disable-line no-eval
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/index.tsx:25]: no eslint-dsiable are required here too...these has been added with recent changes to master

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/index.tsx [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+  removed_at: string; // eslint-disable-line no-eval
+  state: string;
+}
+
+const Sent: React.FC = () => {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/index.tsx:30]: Can you change this to a more appropriate name?

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/styles.ts [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+
+const useStyles = makeStyles((theme) => ({
+  table: {
+    maxHeight: '23.1875rem',
+  },
+  avatarBackground: {
+    backgroundColor: theme.palette.secondary.main,
+    width: '2.56rem',
+    height: '2.56rem',
+    color: '#FFF',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/Sent/styles.ts:11]: we need to take every value from theme so it is easier for @chandankumar4 when he modifies it.
can you change these fixed values and take them from theme

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/index.tsx [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+import useStyles from './styles';
+
+interface TabPanelProps {
+  children: React.ReactNode;
+  index: any;
+  value: any;
+}
+
+// TabPanel ise used to implement the functioning of tabs
+function TabPanel(props: TabPanelProps) {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/index.tsx:16]: use const TabPanel: React.FC<TabPanelProps> = () => {}

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/styles.ts [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+  table: {
+    maxWidth: '63.75rem',
+    minWidth: '39.0625rem',
+    maxHeight: '23.1875rem',
+  },
+  avatarBackground: {
+    backgroundColor: theme.palette.secondary.main,
+    width: '2.56rem',
+    height: '2.56rem',
+    color: '#FFF',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/styles.ts:22]: from theme

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/styles.ts [hunk 11]
```diff
@@ -0,0 +1,55 @@
+import { makeStyles } from '@material-ui/core/styles';
+
+const useStyles = makeStyles((theme) => ({
+  toolbar: {
+    maxWidth: '63.75rem',
+    minWidth: '39.0625rem',
+    borderBottom: '1px solid #e8e8e8',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/styles.ts:7]: from theme

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/styles.ts [hunk 12]
```diff
@@ -0,0 +1,136 @@
...
+    marginBottom: theme.spacing(1.25),
+  },
+  filter: {
+    display: 'flex',
+    alignItems: 'center',
+    marginLeft: theme.spacing(5),
+  },
+  filterMenu: {
+    marginLeft: theme.spacing(1.25),
+    border: '1px solid rgba(0,0,0,0.05)',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/styles.ts:52]: use the customColors from theme...it has a black color where you can pass the opacity

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/styles.ts [hunk 13]
```diff
@@ -0,0 +1,136 @@
...
+  },
+  menuHeader: {
+    fontSize: '0.75rem',
+  },
+  menuDesc: {
+    fontSize: '0.625rem',
+  },
+  menuOpt: {
+    '&:hover': {
+      background: 'rgba(16, 155, 103, 0.1);',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/styles.ts:128]: from theme...add to it if not present

File: litmus-portal/frontend/src/pages/HomePage/index.tsx [hunk 14]
```diff
@@ -49,14 +56,15 @@ const HomePage = () => {
   const classes = useStyles();
 
   const user = useActions(UserActions);
-
-  useQuery(GET_USER, {
+  const [open, setOpen] = React.useState(true);
+  const { loading } = useQuery(GET_USER, {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/pages/HomePage/index.tsx:60]: add typesciprt models to your data and query variables

Comment (arkajyotiMukherjee) [reply litmus-portal/frontend/src/pages/HomePage/index.tsx:60]: look at workflowData.ts in models folder for reference

File: litmus-portal/frontend/src/pages/HomePage/style.ts [hunk 15]
```diff
@@ -12,7 +12,10 @@ const useStyles = makeStyles((theme) => ({
     marginTop: theme.spacing(3),
     marginLeft: theme.spacing(6),
   },
-
+  backdrop: {
+    zIndex: theme.zIndex.drawer + 1,
+    color: '#fff',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/pages/HomePage/style.ts:17]: from theme

File: litmus-portal/frontend/src/pages/LoginPage/index.tsx [hunk 16]
```diff
@@ -16,9 +16,20 @@ interface authData {
 const LoginPage = () => {
   const user = useActions(UserActions);
   const classes = useStyles();
+  let urlUser: string = '';
+
+  let urlPass: string = '';
+  if (window.location.hash.length > 0) {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/pages/LoginPage/index.tsx:22]: dont use window.location 
use the useLoaction() hook from react-router-dom that gives you these hash
like this
const {hash} = useLocation()

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]

File: litmus-portal/backend/auth/go.sum [hunk 17]
```diff
@@ -13,19 +13,25 @@ github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSs
 github.com/dgrijalva/jwt-go v3.2.0+incompatible h1:7qlOGliEKZXTDg6OTjfoBKDXWrumCAMpl/TFQ4/5kLM=
 github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
 github.com/dgryski/trifles v0.0.0-20190318185328-a8d75aae118c/go.mod h1:if7Fbed8SFyPtHLHbg49SI7NAdJiC5WIA09pe59rfAA=
+github.com/gin-contrib/cors v1.3.1 h1:doAsuITavI4IOcd0Y19U4B+O0dNWihRyX//nn4sEmgA=
 github.com/gin-contrib/cors v1.3.1/go.mod h1:jjEJ4268OPZUcU7k9Pm653S7lXUGcqMADzFA61xsmDk=
+github.com/gin-contrib/sse v0.1.0 h1:Y/yl/+YNO8GZSjAhjMsSuLt29uWRFHdHYUb5lYOV9qE=
 github.com/gin-contrib/sse v0.1.0/go.mod h1:RHrZQHXnP2xjPF+u1gW/2HnVO7nvIa9PG3Gm+fLHvGI=
```
Comment (oumkale) [inline litmus-portal/backend/auth/go.sum:19]: Remove those changes it is not require from go.sum.

**Comment by arkajyotiMukherjee** [comment]
Welcome modal is coming again on reloads @Saranya-jena

**Comment by ishangupta-ds** [comment]
> Welcome modal is coming again on reloads @Saranya-jena

@arkajyotiMukherjee we tried to debug this, its because the backend changes required to go in before this PR is not yet merged, the gql schema has been changed in the frontend with this PR but the backend hasn't been updated we can't test this PR even with betterCI till PR #1982 is merged. cc: @rajdas98 @Saranya-jena @amityt @Sanjay1611

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx [hunk 18]
```diff
@@ -0,0 +1,199 @@
...
+      );
+    },
+    onError: () => {},
+    refetchQueries: [
+      { query: GET_USER, variables: { username: userData.username } },
+    ],
+  });
+
+  // mutation to decline the invitation
+  const [declineInvite] = useMutation(DECLINE_INVITE, {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx:62]: type usemutation hooks

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx [hunk 19]
```diff
@@ -0,0 +1,199 @@
...
+  // for response data
+  const [rows, setRows] = useState<ReceivedInvitation[]>([]);
+
+  const { userData } = useSelector((state: RootState) => state);
+
+  // stores the user whose invitation is accepted/declined
+  const [acceptDecline, setAcceptDecline] = useState<string>('');
+
+  // mutation to accept the invitation
+  const [acceptInvite] = useMutation(ACCEPT_INVITE, {
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx:47]: type usemutation hooks

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx [hunk 20]
```diff
@@ -0,0 +1,312 @@
...
+              !memberList.has(data.username) && users.push(data)
+          );
+        }
+        setRows(users);
+      }
+    },
+  });
+
+  // mutation to send invitation to selected users
+  const [SendInvite, { error: errorB, loading: loadingB }] = useMutation(
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx:116]: type usemutation hooks

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx (hunk 19 above)
Comment (arkajyotiMukherjee) [reply litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx:47]: put the interfaces in a separate file in models folder

File: litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx [hunk 21]
```diff
@@ -0,0 +1,312 @@
...
+      ) : (
+        <div>
+          <Typography className={classes.Header}>
+            Invite <strong>new member</strong>
+          </Typography>
+          <Toolbar className={classes.toolbar}>
+            <div
+              style={{
+                display: 'flex',
+                flexDirection: 'row',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/TeammingTab/InviteNew/Invite/index.tsx:219]: this line can be removed,,,display flex is by default row

File: litmus-portal/frontend/src/components/Sections/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx [hunk 22]
```diff
@@ -66,29 +68,54 @@ const NewUserModal: React.FC<NewUserModalProps> = ({
...
-            <Typography className={classes.typo} align="center">
-              A new user was <strong>successfully created </strong>
-            </Typography>
-          </div>
-          <div className={classes.textSecond}>
-            <Typography className={classes.typoSub}>
-              A new user was successfully created.Now information about it will
-              be displayed on the user management screen of the application.
-            </Typography>
+        {error.length > 0 ? (
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/components/Sections/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx:71]: change this to error.length
0 is a falsey value in javascript

File: litmus-portal/frontend/src/theme/index.tsx [hunk 23]
```diff
@@ -93,6 +99,9 @@ function customTheme(options: ThemeOptions) {
         },
         gray: '#5D6173',
       },
+      menuOption: {
+        active: 'rgba(16, 155, 103, 0.1)',
```
Comment (arkajyotiMukherjee) [inline litmus-portal/frontend/src/theme/index.tsx:103]: this is a color...can you put this in custom colors.
The entire menuOption object shift inside customColors

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]
can you fix these minor changes

**Review by arkajyotiMukherjee — DISMISSED** [review]
LGTM

**Review by amityt — DISMISSED** [review]
LGTM

**Review by rajdas98 — APPROVED** [review]

**Comment by rajdas98** [comment]
@Saranya-jena Can you resolve the merge conflict?

**Review by ishangupta-ds — APPROVED** [review]

**Review by arkajyotiMukherjee — APPROVED** [review]
