### PR TITLE
fixes #4665 Invalid version details in backend.

### LINKED ISSUE #4665: Ci version error in `updateVersionFormat`
**What happened**:
When all the infra are listed in chaos infrastructure we are getting invalid version format error.
Its due to in `updateVersionFormat` ,here  we are converting version string to integer and "ci" is invalid string for converting into number
Screenshot from 2024-05-22 14-44-02

**Where can this issue be corrected? (optional)**
In `updateVersionFormat` we can ignore the "ci" version string 

**How to reproduce it (as minimally and precisely as possible)**:
Go to all chaos enable infrastructure window 
Screenshot from 2024-05-22 16-36-28

### PR DESCRIPTION
**Pull request by JanhaviAlekar**
fixes #4665

## Proposed changes
In  `updateVersionFormat` , Ignored "ci" because it is not a proper version to convert into Int

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the commit for DCO to be passed.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

### CODE REVIEW

**Review by hrishavjha — APPROVED** [review]

File: chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go [hunk 1]
```diff
@@ -911,11 +911,13 @@ func updateVersionFormat(str string) (int, error) {
 	var versionInt int
 	versionSlice := strings.Split(str, ".")
 	for i, val := range versionSlice {
-		x, err := strconv.Atoi(val)
-		if err != nil {
-			return -1, err
+		if val != CIVersion {
```
Comment (Jonsy13) [inline chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go:914]: I think with this change, It will return `0` incase of CI version. Which is not expected. Either this function would need change to send version in string form and then send value as `ci` or In frontend, we can have a check if returned value is `0`, then we should show `ci` in frontend.

Comment (SarthakJain26) [reply chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go:914]: Please add a check In the parent function to check if the returned value is 0, set the version as ci in the response. Also instead of checking for the CIVersion here, it can be done at function start where you can directly check the str with CIVersion and return `0, nil` in case the version is "ci"

Comment (JanhaviAlekar) [reply chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go]:
```
func (in *infraService) GetVersionDetails() (*model.InfraVersionDetails, error) {
	// Fetching the list of infra compatible versions
	compatibleVersions := utils.Config.InfraCompatibleVersions

	var compatibleArray []string
	_ = json.Unmarshal([]byte(compatibleVersions), &compatibleArray)

	// To find the latest compatible version
	compatibleMap := make(map[int]string)

	// To store the compatible versions in int format
	var compatibleArrayInt []int

	for _, versionStr := range compatibleArray {
		versionInt, err := updateVersionFormat(versionStr)
		if err != nil {
			return &model.InfraVersionDetails{}, err
		}

		compatibleArrayInt = append(compatibleArrayInt, versionInt)
		compatibleMap[versionInt] = versionStr
	}

	// Fetching the latest version
	latestVersion := fetchLatestVersion(compatibleMap)
	return &model.InfraVersionDetails{LatestVersion: compatibleMap[latestVersion], CompatibleVersions: compatibleArray}, nil
}
```
I dont think we need to set the version as ci in the response as its already getting mapped and I guess we are only using compatibleMap for fetching latest Version
compatibleMap  map[0:ci 10:0.1.0 20:0.2.0] )

**Review by amityt — APPROVED** [review]

**Review by namkyu1999 — APPROVED** [review]

**Review by Jonsy13 — APPROVED** [review]
